let choices = [
    {id: 1,
        quest: 'How many bones have I broken?',
        c1: '12',
        c2: '1',
        c3: '0',
        c4: '4',
        correct: '4',
    },
    {id: 2, 
        quest: 'What video game do I have the most time played on?',
        c1: 'Ark Survival Evolved', 
        c2: 'Minecraft', 
        c3: 'Rainbow Six Siege',
        c4: 'World of Warcraft', 
        correct: 'Ark Survival Evolved', 
    },
    {id: 3, 
        quest: 'Who is my favorite combat sports athlete?',
        c1: 'Colby Covington', 
        c2: 'Jon Jones', 
        c3: 'Dan Hooker',
        c4: 'Chael Sonnen',
        correct: 'Dan Hooker',
    },
    {id: 4, 
        quest: 'What is my favorite anime?', 
        c1: 'Naruto',
        c2: 'Tokyo Ghoul',
        c3: 'Demon Slayer',
        c4: 'Attack on Titan',
        correct: 'Demon Slayer',
    },
    {id: 5, 
        quest: 'Who is my favorite music atrist?', 
        c1: 'Lil Pump',
        c2: 'Grimes',
        c3: 'Bruno Mars',
        c4: 'Ski Mask the Slump God',
        correct: 'Ski Mask the Slump God',
    },
    {id: 6, 
        quest: 'What is my favorite genre of music?', 
        c1: 'Hardcore',
        c2: 'Rap',
        c3: 'Indie',
        c4: 'Metal',
        correct: 'Hardcore',
    },
    {id: 7, 
        quest: 'What is my favorite candy?', 
        c1: 'Snickers',
        c2: 'Skittles',
        c3: 'Gummy Krabby Patties',
        c4: 'Sour Patch Kids',
        correct: 'Gummy Krabby Patties',
    },
    {id: 8, 
        quest: 'What was my first car?', 
        c1: '1995 Mitsubishi Eclipse',
        c2: '2003 Honda Civic',
        c3: '2005 Nissan 350z',
        c4: '1992 Toyota Pickup',
        correct: '1995 Mitsubishi Eclipse',
    },
    {id: 9, 
        quest: 'What is my favorite car I have ever owned?', 
        c1: '1995 Mitsubishi Eclipse',
        c2: '2005 Nissan 350z',
        c3: '1992 Toyota Pickup',
        c4: '1991 Chevrolet Camaro',
        correct: '2005 Nissan 350z',
    },
    {id: 10, 
        quest: 'Who is my favorite anime character?', 
        c1: 'Tanjiro Kamado',
        c2: 'Ken Kaneki',
        c3: 'Itachi Uchiha',
        c4: 'Naruto Uzumaki',
        correct: 'Naruto Uzumaki',
    },
    {id: 11, 
        quest: 'What is my dream car?', 
        c1: '2018 Nissan 370z',
        c2: '1994 Nissan Skyline R32 GT-R',
        c3: '1997 BMW e36 Touring',
        c4: '2002 Mazda RX-7',
        correct: '1997 BMW e36 Touring',
    },
    {id: 12, 
        quest: 'What trade am I certified in?', 
        c1: 'Plumbing',
        c2: 'Electrician',
        c3: 'Carpenter',
        c4: 'Welding',
        correct: 'Welding',
    },
    {id: 13, 
        quest: 'What is my favorite live action show?', 
        c1: 'The Walking Dead',
        c2: 'Game of Thrones',
        c3: 'Breaking Bad',
        c4: 'Dexter',
        correct: 'Game of Thrones',
    },
    {id: 14, 
        quest: 'What was my nickname growing up?', 
        c1: 'Bubbles',
        c2: 'Skrilla',
        c3: 'Monkey Butt',
        c4: 'All of the above',
        correct: 'All of the above',
    },
    {id: 15, 
        quest: 'What is my favorite gaming device?', 
        c1: 'PC',
        c2: 'XBOX',
        c3: 'PlayStation',
        c4: 'Nintendo Switch',
        correct: 'XBOX',
    },
    {id: 16, 
        quest: 'What was my first gaming console?',
        c1: 'PlaySation 2',
        c2: 'Nintendo Wii',
        c3: 'XBOX 360',
        c4: 'Nintendo N64',
        correct: 'PlaySation 2',
    },
    {id: 17, 
        quest: 'What breed is my dog Rose?',
        c1: 'Newfoundland',
        c2: 'Black Lab',
        c3: 'Pitbull',
        c4: 'German Shepherd',
        correct: 'Newfoundland',
    },
    {id: 18, 
        quest: 'What are my two cats names?',
        c1: 'Toni and Hershel',
        c2: 'Chico and Harvey',
        c3: 'Chex and Choppa',
        c4: 'Galactus and KitKat',
        correct: 'Chex and Choppa',
    },
    {id: 19, 
        quest: 'What is the fastest I have ever drove a car?',
        c1: '98mph',
        c2: '115mph',
        c3: '177mph',
        c4: '140mph',
        correct: '140mph',
    },
    {id: 20, 
        quest: 'What artist headlined the first concert I ever went to?',
        c1: 'Twenty One Pilots',
        c2: '$uicideboy$',
        c3: 'Ski Mask the Slump God',
        c4: 'Post Malone',
        correct: '$uicideboy$',
    },
]

export default choices;
